[package]
name = "battleship_client"
version = "0.1.0"
edition = "2024"

[dependencies]
battleship_models = { path = "../crates/battleship_models" }
serde_json = { workspace = true }
serde = { workspace = true, features = ["derive"] }
log = "0.4.27"
tokio-tungstenite = { workspace = true }
tokio = { workspace = true }
crossterm = { version = "0.28.1", features = ["event-stream"] }
futures = "0.3.31"
ratatui = "0.29.0"
futures-util = { workspace = true }
color-eyre = "0.6.3"
tracing-error = "0.2.1"
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.20", features = ["env-filter"] }
tracing-appender = "0.2"
directories = "6.0.0"
lazy_static = "1.5.0"
