# Workspace Cargo.toml (at the root of the repository)
    [workspace]
members = [ "battleship_client", "battleship_server", "crates/battleship_models" , "crates/battleship_utilities"]

    [workspace.dependencies]
serde_json = { version = "1.0.142" }
serde = { version = "1.0.219", features = ["derive"] }
tokio-tungstenite = { version = "0.27.0" }
tokio = { version = "1.0.0", features = ["full"] }
futures-util = "0.3.31"
env_logger = "0.11.8"
